/**
 * Scrum Board API
 * This is a wonderful API to manipulate a wonderful Scrum Board
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { v4 as uuidv4 } from 'uuid';


export interface Card {
    id: string;
    /**
     * the name of this card
     */
    name: string;
    /**
     * the description of this card
     */
    description: string;
    state: Card.StateEnum;
}
export class Card implements Card {
  public id: string;
  constructor(public name: string, public description: string, public state: Card.StateEnum) {
    this.id = uuidv4();
  }
}
export namespace Card {
    export type StateEnum = 'todo' | 'in-progress' | 'done';
    export const StateEnum = {
        Todo: 'todo' as StateEnum,
        InProgress: 'in-progress' as StateEnum,
        Done: 'done' as StateEnum
    };
}
